"""Add Test

Revision ID: 0a4728cb3d29
Revises: 3839179df8c0
Create Date: 2024-01-05 16:41:22.805126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a4728cb3d29'
down_revision = '3839179df8c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Parts', sa.String(length=50), nullable=True),
    sa.Column('Regulation_Requirements', sa.String(length=255), nullable=True),
    sa.Column('Expected_Value', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.drop_table('vin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vin',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Activa_110_BS_VI_Year_Code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Activa_110_BS_VI_Plant_Code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Activa_110_BS_VI_Engine_No', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Activa_125_BS_IV_WMI', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Activa_125_BS_IV_Month_Code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Activa_125_BS_TV_Year_Code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Activa_125_BS_IV_Plant_Code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Activa_125_BS_IV_Engine_No', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('Activa_125_BS_VI_WMI', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Activa_125_BS_VI_Month_Code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Activa_125_BS_VI_Year_Code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Activa_125_BS_VI_Plant_Code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Activa_125_BS_VI_Engine_No', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Dio_110_BS_IV_WMI', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Dio_110_BS_IV_Month_Code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Dio_110_BS_TV_Year_Code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Dio_110_BS_IV_Plant_Code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Dio_110_BS_IV_Engine_No', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('Dio_110_BS_VI_WMI', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Dio_110_BS_VI_Month_Code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Dio_110_BS_VI_Year_Code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Dio_110_BS_VI_Plant_Code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Dio_110_BS_VI_Engine_No', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Dio_125_BS_VI_WMI', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Dio_125_BS_VI_Month_Code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Dio_125_BS_VI_Year_Code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Dio_125_BS_VI_Plant_Code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Dio_125_BS_VI_Engine_No', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Grazia_125_BS_IV_WMI', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Grazia_125_BS_IV_Month_Code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Grazia_125_BS_TV_Year_Code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Grazia_125_BS_IV_Plant_Code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Grazia_125_BS_IV_Engine_No', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vin_pkey')
    )
    op.drop_table('test')
    # ### end Alembic commands ###
