"""Add New tabel

Revision ID: 2a2f608f68a6
Revises: 22805677f13a
Create Date: 2024-01-22 15:14:15.191936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a2f608f68a6'
down_revision = '22805677f13a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parts', sa.String(length=50), nullable=True),
    sa.Column('regulation_requirements', sa.String(length=510), nullable=True),
    sa.Column('expected_value', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('ID', sa.INTEGER(), server_default=sa.text('nextval(\'"test_ID_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Parts', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('Regulation_Requirements', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Expected_Value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ID', name='test_pkey')
    )
    op.drop_table('operator_data')
    # ### end Alembic commands ###
