"""Edit data table

Revision ID: 438a54eb08e5
Revises: d8f3da009d01
Create Date: 2024-01-22 15:35:21.402982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438a54eb08e5'
down_revision = 'd8f3da009d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_table', schema=None) as batch_op:
        batch_op.alter_column('result',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_table', schema=None) as batch_op:
        batch_op.alter_column('result',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
