"""ProcessTable date edit

Revision ID: 58146c588aa4
Revises: 0a4728cb3d29
Create Date: 2024-01-16 13:15:48.021432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58146c588aa4'
down_revision = '0a4728cb3d29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_table', schema=None) as batch_op:
        batch_op.alter_column('date_time',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_table', schema=None) as batch_op:
        batch_op.alter_column('date_time',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
