"""Add ProcessTable

Revision ID: 5b98b90a144c
Revises: 
Create Date: 2024-01-04 15:24:13.862738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b98b90a144c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=20), nullable=False),
    sa.Column('admin_id', sa.String(length=50), nullable=False),
    sa.Column('operator_id', sa.String(length=50), nullable=False),
    sa.Column('date_time', sa.Date(), nullable=False),
    sa.Column('vehicle_name', sa.String(length=20), nullable=False),
    sa.Column('vehicle_part', sa.String(length=50), nullable=True),
    sa.Column('requirement', sa.String(length=50), nullable=True),
    sa.Column('scan_output', sa.String(length=50), nullable=True),
    sa.Column('result', sa.Boolean(), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('approve_status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('process_table')
    # ### end Alembic commands ###
