"""Updating AllUsers table

Revision ID: b9e33fe2b175
Revises: cf783471d70d
Create Date: 2024-01-22 11:26:12.977816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9e33fe2b175'
down_revision = 'cf783471d70d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_users', schema=None) as batch_op:
        batch_op.drop_column('designation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designation', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
