"""Add New tabel

Revision ID: d8f3da009d01
Revises: 2a2f608f68a6
Create Date: 2024-01-22 15:20:56.623495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f3da009d01'
down_revision = '2a2f608f68a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Parts', sa.String(length=50), nullable=True),
    sa.Column('Regulation_Requirements', sa.String(length=510), nullable=True),
    sa.Column('Expected_Value', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.drop_table('operator_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parts', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('regulation_requirements', sa.VARCHAR(length=510), autoincrement=False, nullable=True),
    sa.Column('expected_value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='operator_data_pkey')
    )
    op.drop_table('test')
    # ### end Alembic commands ###
